#!/usr/bin/env node

/*
 * @name:           AI Image Renamer
 * @wordpress       Uses AI to rename images during upload for SEO-friendly filenames.
 * @author          Kolja Nolte <kolja.nolte@gmail.com>
 * @copyright       2025-2026 (C) Kolja Nolte
 * @see             https://docs.kolja-nolte.com/viscribe
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Released under the GNU General Public License v2 or later.
 * See: https://www.gnu.org/licenses/gpl-2.0.html
 *
 * @package AIR
 * @license GPL-2.0-or-later
 */


import {execSync}      from 'child_process';
import AdmZip          from 'adm-zip';
import fs              from 'fs';
import path            from 'path';
import {fileURLToPath} from 'url';

/**
 * A constant variable that represents the absolute path of the current module file.
 * It is generated by converting the `import.meta.url` to a file path using the `fileURLToPath` method.
 * This is typically used to retrieve the fully-resolved, platform-specific file path of the
 * JavaScript module that is currently being executed.
 */
const __filename = fileURLToPath(import.meta.url);
/**
 * The `__dirname` variable represents the directory name of the current module.
 * It provides the absolute directory path of the file being executed.
 *
 * `__dirname` is particularly useful for resolving file paths relative to the current module's location,
 * such as when working with the filesystem or requiring local files.
 *
 * In CommonJS environments, it is automatically set. In some non-CommonJS configurations,
 * `__dirname` might need to be explicitly defined using `path.dirname(__filename)`.
 */
const __dirname = path.dirname(__filename);

/**
 * Represents the directory path where plugins are located.
 * This is computed as one level up from the current module's directory.
 * The exact path is determined based on the runtime environment and
 * the module's location in the file system.
 *
 * It is typically used to resolve and load plugin files or directories
 * relative to the application structure.
 *
 * @type {string}
 */
const pluginDir = path.join(__dirname, '..');
/**
 * The name of the package.
 */
const packageName = 'viscribe';
/**
 * Represents the name of the zip file, constructed dynamically by appending a `.zip` extension to the package name.
 *
 * @type {string}
 */
const zipFileName = `${packageName}.zip`;
/**
 * The file system path to the ZIP archive.
 */
const zipPath = path.join(pluginDir, zipFileName);

try {
  // Run wp-scripts plugin-zip first
  console.log('Running wp-scripts plugin-zip...');
  execSync('npx wp-scripts plugin-zip', {cwd: pluginDir, stdio: 'inherit'});

  // Add assets/, vendor/, and views/ to the zip
  const zip = new AdmZip(zipPath);

  // Add assets directory (only built files and icons, not source files)
  if (fs.existsSync(path.join(pluginDir, 'assets'))) {
    console.log('Adding assets/ directory...');
    const assetsPath = path.join(pluginDir, 'assets');
    const addLocalAsset = (relativePath) => {
      const filePath = path.join(pluginDir, relativePath);
      if (!fs.existsSync(filePath)) {
        return;
      }

      const zipEntryName = path.posix.join(
          packageName,
          path.dirname(relativePath).split(path.sep).join('/'),
          path.basename(relativePath),
      );

      zip.addFile(zipEntryName, fs.readFileSync(filePath));
    };

    addLocalAsset('assets/js/index.js');
    addLocalAsset('assets/js/index.asset.php');
    addLocalAsset('assets/css/styles.min.css');

    if (fs.existsSync(path.join(assetsPath, 'icons'))) {
      zip.addLocalFolder(
          path.join(assetsPath, 'icons'),
          `${packageName}/assets/icons`,
      );
    }
  }

  // Add vendor directory
  if (fs.existsSync(path.join(pluginDir, 'vendor'))) {
    console.log('Adding vendor/ directory...');
    zip.addLocalFolder(
        path.join(pluginDir, 'vendor'),
        `${packageName}/vendor`,
    );
  }

  // Add composer.json so shipped Composer dependencies can be traced by review tools.
  if (fs.existsSync(path.join(pluginDir, 'composer.json'))) {
    console.log('Adding composer.json...');
    zip.addLocalFile(
        path.join(pluginDir, 'composer.json'),
        `${packageName}/`,
    );

    zip.addLocalFile(
        path.join(pluginDir, 'composer.lock'),
        `${packageName}/`,
    );
  }

  // Add views directory
  if (fs.existsSync(path.join(pluginDir, 'views'))) {
    console.log('Adding views/ directory...');
    zip.addLocalFolder(
        path.join(pluginDir, 'views'),
        `${packageName}/views`,
    );
  }

  // Add languages directory if present.
  if (fs.existsSync(path.join(pluginDir, 'languages'))) {
    console.log('Adding languages/ directory...');
    zip.addLocalFolder(
        path.join(pluginDir, 'languages'),
        `${packageName}/languages`,
    );
  }

  // Remove development and system files from the zip.
  console.log('Removing development and system files...');
  const entries = zip.getEntries();
  const entriesToDelete = [];
  for (const entry of entries) {
    if (
        entry.entryName.match(/\.md$/i) ||
        entry.entryName.match(/\.DS_Store$/i) ||
        entry.entryName.match(/\/viscribe\.zip$/i) ||
        entry.entryName.match(/\/phpcs\.xml\.dist$/i) ||
        entry.entryName.match(/\/(\.distignore|\.babelrc|\.eslintignore|\.eslintrc\.json)$/i) ||
        //entry.entryName.match(/\/vendor\/bin(\/|$)/i) ||
        entry.entryName.match(/\/vendor\/.*\/(docs|dist|tests|other)(\/|$)/i) ||
        entry.entryName.match(/\/vendor\/(dealerdirect|kint-php|phpcsstandards|phpstan|squizlabs)(\/|$)/i) ||
        //entry.entryName.match(/\/vendor\/.*\/(psalm\.xml|splitsh\.json|build-phar\.sh)$/i) ||
        entry.entryName.match(/build-phar\.sh$/i) ||
        entry.entryName.match(/\/vendor\/.*\/CHANGELOG$/i) ||
        entry.entryName.match(/\/vendor\/.*\/README\.(md|rst|txt)$/i)
    ) {
      entriesToDelete.push(entry);
    }
  }
  for (const entry of entriesToDelete) {
    zip.deleteFile(entry);
  }

  // Save the modified zip
  zip.writeZip(zipPath);

  console.log(`✓ ${zipFileName} created with built assets/, vendor/, and views/ included`);
} catch (error) {
  console.error('Failed to create zip file:', error);
  process.exit(1);
}
